### ISSUE TITLE
Performance issue: Index needed on contribution_id field in cdntaxreceipts_log_contributions

### ISSUE THREAD

**Issue by lolas-freeform** [jake-mw/CDNTaxReceipts#29]
I found that part of the underlying performance problem is due to this issue: We need an index on the contribution_id field in cdntaxreceipts_log_contributions. Even without using the hooks the "Receipts not issued" report is running into problems until I add this index. It will help with a number of the other queries in the extension as well. There are quite a few joins on this field.

**Comment by jake-mw** [comment]
Good catch. Thank you.

From: lolas-freeform
Reply-To: jake-mw/CDNTaxReceipts
Date: Wednesday, June 24, 2015 at 9:36 AM
To: jake-mw/CDNTaxReceipts
Subject: [CDNTaxReceipts] Performance issue: Index needed on contribution_id field in cdntaxreceipts_log_contributions (#29)


I found that part of the underlying performance problem is due to this issue: We need an index on the contribution_id field in cdntaxreceipts_log_contributions. Even without using the hooks the "Receipts not issued" report is running into problems until I add this index. It will help with a number of the other queries in the extension as well. There are quite a few joins on this field.

**Comment by lolas-freeform** [comment]
This is in the latest release
