### ISSUE TITLE
Best practices on cancelling tax receipts?

### ISSUE THREAD

**Issue by kasiawaka** [jake-mw/CDNTaxReceipts#35]
What is your experience on cancelling tax receipts? Would it be useful to have a way in the extension to mark a tax receipt as cancelled? I may have funding available for this (once client agrees) - could you let me know if this is even a good idea and what would be involved in implementing this?

**Comment by jake-mw** [comment]
Current practice:
1. Change the Contribution status to 'canceled' -- perhaps entering a note specifying the reason for voiding the receipt.
2. Re-enter the contribution details as a new contribution, and issue the new receipt with corrected details.

I'm not sure how these come out in the "receipts issued" report, to be honest. If it doesn't already come out as having been canceled, that would be an easy change to the report.

I also think the ability to void a tax receipt without cancelling the contribution would be a helpful addition. There might be some small tricky bits in how we organize the interface around this, but overall shouldn't be difficult. I think we would want strict permission controls around who is allowed to cancel a tax receipt.

**Comment by KarinG** [comment]
Hi Kasia - from what I understand - voiding a tax receipt can mean having to inform CRA about it - so very strict permissions are a must. One of my projects will clear this out themselves in phpMyAdmin; for other projects - I'll do this in mysql when asked. It's rare enough that this has worked - though it would be nice to get this in a GUI.

**Comment by kasiawaka** [comment]
Yes, I believe I understand the requirements about informing CRA about the cancelled receipt and sending that info to the donor as well. The case scenario the client provided is that they issued a tax receipt but the donor entered incorrect information on the contribution form - the donor didn't understand the option "in honour of" and entered mother's name on the contribution form, not donor's own information. The tax receipt was issued in the wrong name. They will have to cancel the receipt and issue a new one. Yes, they will cancel the contribution (and I will check and report what happens on the "receipt issued" report once the contribution the receipt was for, was cancelled) and create a new one. Ideally, there would be a way in the system to mark a receipt as cancelled - so that the receipt is still saved in the system but the watermark displays the "cancelled" text and there is a way to run a report to see all cancelled reports? Would you think this is a good idea? For sure, there would have to be a new permission added to control who can cancel a receipt. 
Would it make sense to cancel a tax receipt when the contribution is cancelled?

I understand the idea of deleting a tax receipt directly from the database (I assume that's what you meant, Karen?) - which works great for test receipts for fake transactions. In this case, I assumed we would want to keep the record of that cancelled receipt in CiviCRM, just mark it as cancelled (since the receipt was already distributed to the donor, we can't simply, as my understanding of the CRA rules goes, delete a receipt). 

Does this make sense as a new feature? If so, would you be able to estimate it? I may be able to get funds for it.

**Comment by KarinG** [comment]
When we make edits in the database directly it would be in the reconciliation of monies/pre-auditing process - prior to sending the taxreceipts to the donor; Once a receipt has been sent to the donor then it indeed should not be deleted; cancelled - is a good word - perhaps time to add a receipt_status field in cdntaxreceipts_log

**Comment by lolas-freeform** [comment]
We also have a customer with current interest and funding to do this. Maybe we should chat?

**Comment by jake-mw** [comment]
Lola, does it make sense for you and Kasia to work together on this, and let Karin & I know when you have some detail worked out on how you want to implement this?

I'm happy to be involved as well -- either in the spec phase or implementation -- but I think we might as well let those with funding get started on it.

**Comment by lolas-freeform** [comment]
Kasia and I had a discussion on what would be required to implement a "Cancelled" status on receipts. This was what we came up with:

- Add a column receipt_status - The options are receipt_status = issued or cancelled
- This column is visible on the tax receipt display screen
- The tax receipt display screen has a button to cancel a tax receipt
- Pressing the cancel button pops up a confirmation with OK and Cancel
- PDF of the receipt can still be generated by clicking tax receipt button but no email is sent automatically, even if email sending is currently enabled
- PDF shows "Cancelled" in similar place where preview or duplicate usually displays
- Report of issued receipts shows status column and can be filtered by status

**Comment by jake-mw** [comment]
I like this and would support its addition to the project. Karin?

A couple of questions:
1. Is there a need for a special permission, 'cancel tax receipts', different from 'issue tax receipts'? I'm going back and forth on whether this fine-grained control is needed. Because you suggest that we 'cancel' but not 'delete' the receipt record, an audit trail is maintained so I'm not sure if a separate permission is strictly necessary.
2. When a receipt has been canceled for a contribution - can a new receipt then be issued for that contribution? How do we display both the original (canceled) receipt, and the new receipt?

**Comment by lolas-freeform** [comment]
Good questions. We talked about the first point on a separate permission. We felt that it was optional since it should be very rare for a staff member with the "Issue Tax Receipts" permission to make a mistake in cancelling a receipt. Another question is whether this should update the uid field with the cancelling user's uid.

We didn't discuss your second point. I think it would be best but perhaps more challenging to show all receipts related to the contribution. Perhaps cancelled ones should display lower than current ones and with a different background colour. In practice most receipts will be cancelled and the contributions will be cancelled as well because they were recorded against the wrong contact etc.

**Comment by lolas-freeform** [comment]
For point 2 I would suggest that for a first version of this feature we can say, "No, a new receipt cannot be issued for this contribution." A future enhancement would allow that and deal with how to display it.

**Comment by jake-mw** [comment]
I think point 2 is an important one to address for many client use-cases, but I would agree that it can be left for future development. We would want to make sure the UI for this is clear and doesn't lead to confusion as to which receipt is the real one, and which are 'canceled' ones.

I think there should be some kind of logging of who canceled the receipt. If there were a fraud investigation related to issuance of tax receipts, that information would be an important part of the audit trail. It should probably be an additional field in the db table, though (canceled_by, canceled_ip, and canceled_date?) instead of replacing the original information.

**Comment by jake-mw** [comment]
Just chatted very briefly with Karin -- I think what you've laid out here is good. I assume one of you (Kasia or Lola) have some funding to make it happen?

**Comment by lolas-freeform** [comment]
We also agreed that the ability to Un-cancel a receipt could be left for future development. While not hard to do it is also not required by either of the clients we currently have providing some funding.
