### ISSUE TITLE
Feature request - Ability to log tax receipts without issuing them

### ISSUE THREAD

**Issue by lolas-freeform** [jake-mw/CDNTaxReceipts#40]
We have the requirement to log tax receipts before issuing them to support the following workflow: A large batch of tax receipts are temporarily logged then a report is run on the tax receipt batch for the current year. This report is carefully compared to other contribution reports by the staff and other official reports are generated. The tax receipts batch is then "issued", ie. printed and mailed once it is approved.

I believe this would require a new boolean column: "issued".

Certainly we could create this feature as a separate extension that uses a copy of the tables to temporarily store the batch and our reports could work on that. However if it would be useful to other users it would be best placed in the main extension.

**Comment by jake-mw** [comment]
I assume you have looked at the "tax receipts to be issued" report, and found that this does not adequately address your need to review the tax receipts before they get issued? I suppose that report lists contributions, but not aggregated receipt amounts...

That being said, I think there are other reasons logging-before-issuing makes sense. For one, then the receipt gets assigned an ID (the primary key of the cdntaxreceipts_log) table before the document gets generated. This would allow me to assign a serial receipt number, rather than one tied to Contribution ID, for those clients who are nervous about whether or not the CRA really requires a serial numbering scheme. That would be nice.

Per our other conversation, I would suggest adding a column to the receipt table, receipt_status, and that can be 'in review', 'issued', or 'voided' (or whatever language makes sense to you).

Would you picture this disrupting the current workflow for current users in any way? (Are you proposing UI changes, or only schema changes, for the main extension?)

**Comment by lolas-freeform** [comment]
The "tax receipts to be issued" report shows each contribution separately. In the other issue #41 I mention a client that has particular requirements for grouping of contributions. I agree that the column name **receipt_status** makes sense. It could be used for #35 as well.

**Comment by KarinG** [comment]
How about we add a Group by option Contact (dbAlias sum them up) in the receipts not issued report? Receipt status makes sense for cancelled receipts, we could also decide to then log a mark Preview receipt as previewed. Preview status/terminology we already use.

**Comment by lolas-freeform** [comment]
The report can't meet our requirement here due to a number of custom fields in use. For this use case we already have a report built in Drupal.

I think that logging the receipt when it is previewed goes against the current usage of being able to view a receipt without affecting the db. If it is to be implemented at all I think that logging without issuing is a fundamentally different action than previewing.

**Comment by lolas-freeform** [comment]
We are not going to move forward on this feature for now. We will log into a temporary batch table created by another extension or module for our "pre-issuing" reporting stage. However, I could see this temporary batch feature being useful for other clients in the future when their verification process needs more detailed info than the summary table they get on the "Issue Annual" or "Issue Aggregate" screens. If the extension ever gets the feature it could be stored in a separate table such  as  cdntax_receipts_log_batch_2016_01_04.
