### ISSUE TITLE
Queue processing for large receipt runs

### ISSUE THREAD

**Issue by jake-mw** [jake-mw/CDNTaxReceipts#42]
The root issue in #38  -- timeouts when running large batches of receipts on certain servers -- means that large batches of tax receipts can be lost if the server times out half way through processing. Once the server times out, the receipts that were already issued can't be issued again. But the printout hasn't yet been downloaded. So there's a lot of cleanup that needs to happen in order to rescue a half-finished process: need to clean up the tax archive, remove entries from the database log (through the mysql backend) and then try to issue again using a smaller batch size.

While some folks can change their server settings to allow longer execution time, this isn't available to everyone. Nor are most users able (nor should they) manually clean up the underlying database tables.  And if it's a mix of hardcopy & email receipts that are being issued when the timeout occurred, it becomes a real mess.

We should probably queue up the expensive operations when issuing large batches of receipts (e.g. the individual emails sent to the email archive), and process the queue in a separate process.

**Comment by adixon** [comment]
Yes, and also setup the code so that if it stops part way through it leaves things in a state that can be auto-recovered. Even queue processing can be interrupted.

**Comment by gboudrias** [comment]
Hello! Any updates on this?

**Comment by KarinG** [comment]
@adixon is looking at solving this server side for one of our projects this week - we'll make sure to loop back here [and please do poke us next week - if we haven't].

**Comment by adixon** [comment]
Well, not a solution to this issue, more of a work around. 

One cause of timeouts (but not necessarily the only one) is due to the way the extension sends out each receipt separately. If you are using an external smtp server, that requires (blocking) connection/disconnection overhead. 

One workaround is to not use an external smtp setting in CiviCRM, but instead just use the default (mail) option, and configure the server to use the external smtp server for all outgoing mail. Dropping mail to the local server is much faster, and allows that local server to batch out the mail in a non-blocking queue.

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
