### ISSUE TITLE
Feature request - Configurable Reporting Periods

### ISSUE THREAD

**Issue by lolaslade** [jake-mw/CDNTaxReceipts#48]
The extension assumes that receipts will be batch generated for a calendar year. There are some use cases where this is not true. For example political parties need to generate separate receipts and reports for a campaign period. To support this I would like to see a screen for configurable "Reporting Periods" that allows a date range to be given a label. Those labelled date ranges would be available in the drop down selection for "Annual" and "Aggregate" Tax receipts. They would also be available in the receipt reports. Several calendar years would be pre-configured as "Reporting Periods" on installation.

**Comment by jake-mw** [comment]
Lola, I'm curious about this use case, only because I have worked with
several political parties and never run into this requirement. But I know
regulations can be different in different jurisdictions.

**Comment by lolas-freeform** [comment]
It's a request we got from a political party we are working with. I have done any background research.

**Comment by KarinG** [comment]
I'm currently working with a major political party and Tax receipting requirements are annually by calendar year - because Canadians must file their Tax Returns annually. Reporting periods can differ and are indeed dependent on Elections - but that's on the reporting side of things - not the issuing of the Tax Receipts.

**Comment by lolas-freeform** [comment]
This particular party uses the Reporting Periods for both reporting and issuing. This could mean multiple receipts per donor in a calendar year. However, this is not very different as a requirement from groups that issue a single receipt for each donation.

At the very least it sounds like configurable "Reporting Periods" would be useful to your client for Reporting.

**Comment by KarinG** [comment]
It's not an issue though as the reporting is already configurable. Are you not able to use your aggregate functionality to issue Tax Receipts for say e.g. Jan01 - Sep30? Or any period - you can select on the Find Contributions screen?

**Comment by jake-mw** [comment]
I think what I'm hedging on, with the "reporting periods" approach, is that
this seems like something that adds administrative complexity
year-over-year, when in the vast majority of use cases it's not needed.

One way around this could be to set up the "reporting periods" in a custom
implementation, rather than as part of the extension. This could be
accomplished, without hacking any extension code, by:

1. Putting a custom field on the Contribution, which is configured with
"reporting periods" as selectable options. This field could be filled in
automatically in custom php code, based on receive date, or it could be
user-selectible per contribution.
2. Using hook_cdntaxreceipts_alter_receipt(&$receipt) to alter the
"received date" on the receipt, changing it from the default for aggregate
receipts (Jan 1 - Dec 31 20xx), to something appropriate based on the
reporting period(s) selected for the contained contributions.
3. You can "Find Contributions" based on this custom field, and issue
Aggregate Receipts as usual for the desired reporting period.
4. If we exposed contribution custom fields as a filter in the reports (per
your other suggestion), you would also get filtering by reporting period
there.

Would this approach be something workable, until we are certain this use
case is needed more broadly?

**Comment by lolas-freeform** [comment]
Workable in theory but not as usable as I would like to provide for this client. This is also the client that can't use the aggregate feature.

What is the "administrative complexity year-over-year" that you anticipate? Configuring the reporting periods? If the extension enables a number of past and upcoming years as periods by default upon installation there is nothing for the client to do for a very long time.

**Comment by KarinG** [comment]
I tend to agree this would be adding complexity - for - (it sound like) just one use case - but perhaps I'm not understanding what you'd like to do. Shall we try touch base by Skype - next week?
