### ISSUE TITLE
Add Contribution and Contact custom fields to reports as columns and filters

### ISSUE THREAD

**Issue by lolaslade** [jake-mw/CDNTaxReceipts#49]
It would be useful to have the Contribution and Contact custom fields on the reports as columns and filters.

**Comment by lolas-freeform** [comment]
I've committed a tiny change that adds the custom fields to the "Receipts Not Issued" report. The same change caused an error on the "Receipts Issued" report and I will have to look into that later.

**Comment by jake-mw** [comment]
Thanks! I don't know about the error, but the "receipt issued" report may
run into complexity when you have an aggregate receipt - two or more
contributions attached to a single receipt. The error may be because we
don't ever join the civicrm_contribution table in that report.

I presume we'll end up with duplicate rows in the case where there is an
aggregate receipt, and Contribution custom fields have been selected.

It would be important to make sure we still have a single row per receipt,
if no contribution custom fields have been selected.

**Comment by adixon** [comment]
Nice little patch, but kind of weird in that it adds the custom fields without the base contribution fields.

I was looking at it because of a request to include payment instrument and receive date in the report, which of course only makes sense because they're using single receipts.

Does it maybe make more sense to have a single-receipt only version of this report that allows more related contribution data? Or is there a solution that keeps to just one report? I guess it'd have to be like the summary reports that provide multiple lines underneath if there were multiple contributions attached to the receipt.

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
