### ISSUE TITLE
1.3.2 tag?

### ISSUE THREAD

**Issue by JoeMurray** [jake-mw/CDNTaxReceipts#62]
Could you put a tag on master for 1.3.2? It seems that info.xml was updated with 1.3.2 five months ago. Unfortunately, one can't use a PR to suggest a tag. Thx.

**Comment by lolas-freeform** [comment]
Agreed. There were a lot of changes including some bugs fixed for 4.7 in 1.3.2. I didn't make a release at the time since typically that hasn't been my responsibility. There are now some schema changes in master so if we do make a release we probably need to update the info.xml and call it 1.3.3 or above.

We should see if we can reproduce the open issue for 4.7 and fix that before a new release though.

**Comment by KarinG** [comment]
@jake-mw and I are planning to spend some quality time on CDN TaxReceipts at CiviCamp Montreal next month; 4.7 release and non_deductible_amount reconciliation are top of the agenda.

**Comment by lolas-freeform** [comment]
This can be closed since there is a new release.
