### ISSUE TITLE
Deprecated messages in 4.7

### ISSUE THREAD

**Issue by lolaslade** [jake-mw/CDNTaxReceipts#74]
Using the latest version for 4.7 the logs are filling with quite a few messages. Looks like this happens every time a setting is accessed.
`    Deprecated: Group='CDNTaxReceipts'. Name='receipt_signature'. Defaults should come from metadata `

For an example of the new format see: https://issues.civicrm.org/jira/browse/CRM-17507

Thanks for the 4.7 update by the way!

**Comment by demeritcowboy** [comment]
Just want to renotify about this since in 5.22 CRM_Core_BAO_Setting::setItem is going to start popping up warnings onscreen not just debug_log_message (depending on logging settings), and it seems to be used a lot.

https://github.com/civicrm/civicrm-core/pull/15975

I can help with testing if needed.

**Comment by KarinG** [comment]
@demeritcowboy - because you asked! :-)

I've taking a very first stab at this -> mostly search/replace - it's a WIP that I just posted for comment/feedback: 
https://github.com/jake-mw/CDNTaxReceipts/pull/97/files

Any Comments/feedback welcome! I've only tested for syntax/not for functionality. There is one particular one that I'm not sure how to handle. 

Cc: @jake-mw

**Comment by demeritcowboy** [comment]
Thanks will take a look.

**Comment by demeritcowboy** [comment]
Regarding the unsure one, the Upgrader/Base seems based on an older version of civix. So I guess two possible choices are:
* Keep doing what you're doing with version setting.
* Look at bringing that base file up to date with a more current version of civix. I can't immediately see how much work that is but in particular the call in onInstall() to setCurrentVersion, which is causing the sql issue, isn't in the latest civix-generated file.

**Comment by demeritcowboy** [comment]
Hi just checking in on this since I think 5.22 is being released next week? Would it help if I put up an alternate PR with the various changes?

I don't want to make it sound like there is a super-hurry - people who have it already installed probably won't notice any warnings and on a live site probably have screen errors turned off. But anyone installing it to test it out will see a red warning right after install, and then a slew of warnings on the settings page which is usually where you go right after install. So it mostly might just scare away new users.

**Comment by KarinG** [comment]
Sorry - I've not had a chance yet to get back to this - though it's high priority! I don't think we can release though in the middle of Tax Receipt season. But at least we could wrap it up and get it merged into master [if anyone wants to pull]. Yes please do put up an alternate PR and I'll test that.

**Comment by KarinG** [comment]
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD
